\version "2.24"
\include "emoji-people-body.ily"

\paper {
  #(set-paper-size "a4")
  top-margin = 15\mm
  bottom-margin = 15\mm
  left-margin = 15\mm
  right-margin = 15\mm
}

\header {
  title = "OpenMoji Icons Cheat Sheet"
  tagline = ##f
}

\markuplist {
  \override-lines #'(baseline-skip . 7)
  \wordwrap-lines {
    \box \pad-markup #1 \line { \vcenter \anatomicalHeart \hspace #1 \vcenter "\\anatomicalHeart" }
    \box \pad-markup #1 \line { \vcenter \artist \hspace #1 \vcenter "\\artist" }
    \box \pad-markup #1 \line { \vcenter \astronaut \hspace #1 \vcenter "\\astronaut" }
    \box \pad-markup #1 \line { \vcenter \baby \hspace #1 \vcenter "\\baby" }
    \box \pad-markup #1 \line { \vcenter \babyAngel \hspace #1 \vcenter "\\babyAngel" }
    \box \pad-markup #1 \line { \vcenter \backhandIndexPointingDown \hspace #1 \vcenter "\\backhandIndexPointingDown" }
    \box \pad-markup #1 \line { \vcenter \backhandIndexPointingLeft \hspace #1 \vcenter "\\backhandIndexPointingLeft" }
    \box \pad-markup #1 \line { \vcenter \backhandIndexPointingRight \hspace #1 \vcenter "\\backhandIndexPointingRight" }
    \box \pad-markup #1 \line { \vcenter \backhandIndexPointingUp \hspace #1 \vcenter "\\backhandIndexPointingUp" }
    \box \pad-markup #1 \line { \vcenter \balletDancer \hspace #1 \vcenter "\\balletDancer" }
    \box \pad-markup #1 \line { \vcenter \bitingLip \hspace #1 \vcenter "\\bitingLip" }
    \box \pad-markup #1 \line { \vcenter \bone \hspace #1 \vcenter "\\bone" }
    \box \pad-markup #1 \line { \vcenter \boy \hspace #1 \vcenter "\\boy" }
    \box \pad-markup #1 \line { \vcenter \brain \hspace #1 \vcenter "\\brain" }
    \box \pad-markup #1 \line { \vcenter \breastFeeding \hspace #1 \vcenter "\\breastFeeding" }
    \box \pad-markup #1 \line { \vcenter \bustInSilhouette \hspace #1 \vcenter "\\bustInSilhouette" }
    \box \pad-markup #1 \line { \vcenter \bustsInSilhouette \hspace #1 \vcenter "\\bustsInSilhouette" }
    \box \pad-markup #1 \line { \vcenter \callMeHand \hspace #1 \vcenter "\\callMeHand" }
    \box \pad-markup #1 \line { \vcenter \child \hspace #1 \vcenter "\\child" }
    \box \pad-markup #1 \line { \vcenter \clappingHands \hspace #1 \vcenter "\\clappingHands" }
    \box \pad-markup #1 \line { \vcenter \constructionWorker \hspace #1 \vcenter "\\constructionWorker" }
    \box \pad-markup #1 \line { \vcenter \cook \hspace #1 \vcenter "\\cook" }
    \box \pad-markup #1 \line { \vcenter \coupleWithHeart \hspace #1 \vcenter "\\coupleWithHeart" }
    \box \pad-markup #1 \line { \vcenter \coupleWithHeartManMan \hspace #1 \vcenter "\\coupleWithHeartManMan" }
    \box \pad-markup #1 \line { \vcenter \coupleWithHeartWomanMan \hspace #1 \vcenter "\\coupleWithHeartWomanMan" }
    \box \pad-markup #1 \line { \vcenter \coupleWithHeartWomanWoman \hspace #1 \vcenter "\\coupleWithHeartWomanWoman" }
    \box \pad-markup #1 \line { \vcenter \crossedFingers \hspace #1 \vcenter "\\crossedFingers" }
    \box \pad-markup #1 \line { \vcenter \deafMan \hspace #1 \vcenter "\\deafMan" }
    \box \pad-markup #1 \line { \vcenter \deafPerson \hspace #1 \vcenter "\\deafPerson" }
    \box \pad-markup #1 \line { \vcenter \deafWoman \hspace #1 \vcenter "\\deafWoman" }
    \box \pad-markup #1 \line { \vcenter \detective \hspace #1 \vcenter "\\detective" }
    \box \pad-markup #1 \line { \vcenter \ear \hspace #1 \vcenter "\\ear" }
    \box \pad-markup #1 \line { \vcenter \earWithHearingAid \hspace #1 \vcenter "\\earWithHearingAid" }
    \box \pad-markup #1 \line { \vcenter \elf \hspace #1 \vcenter "\\elf" }
    \box \pad-markup #1 \line { \vcenter \eye \hspace #1 \vcenter "\\eye" }
    \box \pad-markup #1 \line { \vcenter \eyes \hspace #1 \vcenter "\\eyes" }
    \box \pad-markup #1 \line { \vcenter \factoryWorker \hspace #1 \vcenter "\\factoryWorker" }
    \box \pad-markup #1 \line { \vcenter \fairy \hspace #1 \vcenter "\\fairy" }
    \box \pad-markup #1 \line { \vcenter \family \hspace #1 \vcenter "\\family" }
    \box \pad-markup #1 \line { \vcenter \familyAdultAdultChild \hspace #1 \vcenter "\\familyAdultAdultChild" }
    \box \pad-markup #1 \line { \vcenter \familyAdultAdultChildChild \hspace #1 \vcenter "\\familyAdultAdultChildChild" }
    \box \pad-markup #1 \line { \vcenter \familyAdultChild \hspace #1 \vcenter "\\familyAdultChild" }
    \box \pad-markup #1 \line { \vcenter \familyAdultChildChild \hspace #1 \vcenter "\\familyAdultChildChild" }
    \box \pad-markup #1 \line { \vcenter \familyManBoy \hspace #1 \vcenter "\\familyManBoy" }
    \box \pad-markup #1 \line { \vcenter \familyManBoyBoy \hspace #1 \vcenter "\\familyManBoyBoy" }
    \box \pad-markup #1 \line { \vcenter \familyManGirl \hspace #1 \vcenter "\\familyManGirl" }
    \box \pad-markup #1 \line { \vcenter \familyManGirlBoy \hspace #1 \vcenter "\\familyManGirlBoy" }
    \box \pad-markup #1 \line { \vcenter \familyManGirlGirl \hspace #1 \vcenter "\\familyManGirlGirl" }
    \box \pad-markup #1 \line { \vcenter \familyManManBoy \hspace #1 \vcenter "\\familyManManBoy" }
    \box \pad-markup #1 \line { \vcenter \familyManManBoyBoy \hspace #1 \vcenter "\\familyManManBoyBoy" }
    \box \pad-markup #1 \line { \vcenter \familyManManGirl \hspace #1 \vcenter "\\familyManManGirl" }
    \box \pad-markup #1 \line { \vcenter \familyManManGirlBoy \hspace #1 \vcenter "\\familyManManGirlBoy" }
    \box \pad-markup #1 \line { \vcenter \familyManManGirlGirl \hspace #1 \vcenter "\\familyManManGirlGirl" }
    \box \pad-markup #1 \line { \vcenter \familyManWomanBoy \hspace #1 \vcenter "\\familyManWomanBoy" }
    \box \pad-markup #1 \line { \vcenter \familyManWomanBoyBoy \hspace #1 \vcenter "\\familyManWomanBoyBoy" }
    \box \pad-markup #1 \line { \vcenter \familyManWomanGirl \hspace #1 \vcenter "\\familyManWomanGirl" }
    \box \pad-markup #1 \line { \vcenter \familyManWomanGirlBoy \hspace #1 \vcenter "\\familyManWomanGirlBoy" }
    \box \pad-markup #1 \line { \vcenter \familyManWomanGirlGirl \hspace #1 \vcenter "\\familyManWomanGirlGirl" }
    \box \pad-markup #1 \line { \vcenter \familyWomanBoy \hspace #1 \vcenter "\\familyWomanBoy" }
    \box \pad-markup #1 \line { \vcenter \familyWomanBoyBoy \hspace #1 \vcenter "\\familyWomanBoyBoy" }
    \box \pad-markup #1 \line { \vcenter \familyWomanGirl \hspace #1 \vcenter "\\familyWomanGirl" }
    \box \pad-markup #1 \line { \vcenter \familyWomanGirlBoy \hspace #1 \vcenter "\\familyWomanGirlBoy" }
    \box \pad-markup #1 \line { \vcenter \familyWomanGirlGirl \hspace #1 \vcenter "\\familyWomanGirlGirl" }
    \box \pad-markup #1 \line { \vcenter \familyWomanWomanBoy \hspace #1 \vcenter "\\familyWomanWomanBoy" }
    \box \pad-markup #1 \line { \vcenter \familyWomanWomanBoyBoy \hspace #1 \vcenter "\\familyWomanWomanBoyBoy" }
    \box \pad-markup #1 \line { \vcenter \familyWomanWomanGirl \hspace #1 \vcenter "\\familyWomanWomanGirl" }
    \box \pad-markup #1 \line { \vcenter \familyWomanWomanGirlBoy \hspace #1 \vcenter "\\familyWomanWomanGirlBoy" }
    \box \pad-markup #1 \line { \vcenter \familyWomanWomanGirlGirl \hspace #1 \vcenter "\\familyWomanWomanGirlGirl" }
    \box \pad-markup #1 \line { \vcenter \farmer \hspace #1 \vcenter "\\farmer" }
    \box \pad-markup #1 \line { \vcenter \fingerprint \hspace #1 \vcenter "\\fingerprint" }
    \box \pad-markup #1 \line { \vcenter \firefighter \hspace #1 \vcenter "\\firefighter" }
    \box \pad-markup #1 \line { \vcenter \flexedBiceps \hspace #1 \vcenter "\\flexedBiceps" }
    \box \pad-markup #1 \line { \vcenter \foldedHands \hspace #1 \vcenter "\\foldedHands" }
    \box \pad-markup #1 \line { \vcenter \foot \hspace #1 \vcenter "\\foot" }
    \box \pad-markup #1 \line { \vcenter \footprints \hspace #1 \vcenter "\\footprints" }
    \box \pad-markup #1 \line { \vcenter \genie \hspace #1 \vcenter "\\genie" }
    \box \pad-markup #1 \line { \vcenter \girl \hspace #1 \vcenter "\\girl" }
    \box \pad-markup #1 \line { \vcenter \guard \hspace #1 \vcenter "\\guard" }
    \box \pad-markup #1 \line { \vcenter \hairyCreature \hspace #1 \vcenter "\\hairyCreature" }
    \box \pad-markup #1 \line { \vcenter \handWithFingersSplayed \hspace #1 \vcenter "\\handWithFingersSplayed" }
    \box \pad-markup #1 \line { \vcenter \handWithIndexFingerAndThumbCrossed \hspace #1 \vcenter "\\handWithIndexFingerAndThumbCrossed" }
    \box \pad-markup #1 \line { \vcenter \handshake \hspace #1 \vcenter "\\handshake" }
    \box \pad-markup #1 \line { \vcenter \healthWorker \hspace #1 \vcenter "\\healthWorker" }
    \box \pad-markup #1 \line { \vcenter \heartHands \hspace #1 \vcenter "\\heartHands" }
    \box \pad-markup #1 \line { \vcenter \horseRacing \hspace #1 \vcenter "\\horseRacing" }
    \box \pad-markup #1 \line { \vcenter \indexPointingAtTheViewer \hspace #1 \vcenter "\\indexPointingAtTheViewer" }
    \box \pad-markup #1 \line { \vcenter \indexPointingUp \hspace #1 \vcenter "\\indexPointingUp" }
    \box \pad-markup #1 \line { \vcenter \judge \hspace #1 \vcenter "\\judge" }
    \box \pad-markup #1 \line { \vcenter \kiss \hspace #1 \vcenter "\\kiss" }
    \box \pad-markup #1 \line { \vcenter \kissManMan \hspace #1 \vcenter "\\kissManMan" }
    \box \pad-markup #1 \line { \vcenter \kissWomanMan \hspace #1 \vcenter "\\kissWomanMan" }
    \box \pad-markup #1 \line { \vcenter \kissWomanWoman \hspace #1 \vcenter "\\kissWomanWoman" }
    \box \pad-markup #1 \line { \vcenter \leftFacingFist \hspace #1 \vcenter "\\leftFacingFist" }
    \box \pad-markup #1 \line { \vcenter \leftwardsHand \hspace #1 \vcenter "\\leftwardsHand" }
    \box \pad-markup #1 \line { \vcenter \leftwardsPushingHand \hspace #1 \vcenter "\\leftwardsPushingHand" }
    \box \pad-markup #1 \line { \vcenter \leg \hspace #1 \vcenter "\\leg" }
    \box \pad-markup #1 \line { \vcenter \loveYouGesture \hspace #1 \vcenter "\\loveYouGesture" }
    \box \pad-markup #1 \line { \vcenter \lungs \hspace #1 \vcenter "\\lungs" }
    \box \pad-markup #1 \line { \vcenter \mage \hspace #1 \vcenter "\\mage" }
    \box \pad-markup #1 \line { \vcenter \man \hspace #1 \vcenter "\\man" }
    \box \pad-markup #1 \line { \vcenter \manArtist \hspace #1 \vcenter "\\manArtist" }
    \box \pad-markup #1 \line { \vcenter \manAstronaut \hspace #1 \vcenter "\\manAstronaut" }
    \box \pad-markup #1 \line { \vcenter \manBald \hspace #1 \vcenter "\\manBald" }
    \box \pad-markup #1 \line { \vcenter \manBeard \hspace #1 \vcenter "\\manBeard" }
    \box \pad-markup #1 \line { \vcenter \manBiking \hspace #1 \vcenter "\\manBiking" }
    \box \pad-markup #1 \line { \vcenter \manBlondHair \hspace #1 \vcenter "\\manBlondHair" }
    \box \pad-markup #1 \line { \vcenter \manBouncingBall \hspace #1 \vcenter "\\manBouncingBall" }
    \box \pad-markup #1 \line { \vcenter \manBowing \hspace #1 \vcenter "\\manBowing" }
    \box \pad-markup #1 \line { \vcenter \manCartwheeling \hspace #1 \vcenter "\\manCartwheeling" }
    \box \pad-markup #1 \line { \vcenter \manClimbing \hspace #1 \vcenter "\\manClimbing" }
    \box \pad-markup #1 \line { \vcenter \manConstructionWorker \hspace #1 \vcenter "\\manConstructionWorker" }
    \box \pad-markup #1 \line { \vcenter \manCook \hspace #1 \vcenter "\\manCook" }
    \box \pad-markup #1 \line { \vcenter \manCurlyHair \hspace #1 \vcenter "\\manCurlyHair" }
    \box \pad-markup #1 \line { \vcenter \manDancing \hspace #1 \vcenter "\\manDancing" }
    \box \pad-markup #1 \line { \vcenter \manDetective \hspace #1 \vcenter "\\manDetective" }
    \box \pad-markup #1 \line { \vcenter \manElf \hspace #1 \vcenter "\\manElf" }
    \box \pad-markup #1 \line { \vcenter \manFacepalming \hspace #1 \vcenter "\\manFacepalming" }
    \box \pad-markup #1 \line { \vcenter \manFactoryWorker \hspace #1 \vcenter "\\manFactoryWorker" }
    \box \pad-markup #1 \line { \vcenter \manFairy \hspace #1 \vcenter "\\manFairy" }
    \box \pad-markup #1 \line { \vcenter \manFarmer \hspace #1 \vcenter "\\manFarmer" }
    \box \pad-markup #1 \line { \vcenter \manFeedingBaby \hspace #1 \vcenter "\\manFeedingBaby" }
    \box \pad-markup #1 \line { \vcenter \manFirefighter \hspace #1 \vcenter "\\manFirefighter" }
    \box \pad-markup #1 \line { \vcenter \manFrowning \hspace #1 \vcenter "\\manFrowning" }
    \box \pad-markup #1 \line { \vcenter \manGenie \hspace #1 \vcenter "\\manGenie" }
    \box \pad-markup #1 \line { \vcenter \manGesturingNo \hspace #1 \vcenter "\\manGesturingNo" }
    \box \pad-markup #1 \line { \vcenter \manGesturingOk \hspace #1 \vcenter "\\manGesturingOk" }
    \box \pad-markup #1 \line { \vcenter \manGettingHaircut \hspace #1 \vcenter "\\manGettingHaircut" }
    \box \pad-markup #1 \line { \vcenter \manGettingMassage \hspace #1 \vcenter "\\manGettingMassage" }
    \box \pad-markup #1 \line { \vcenter \manGolfing \hspace #1 \vcenter "\\manGolfing" }
    \box \pad-markup #1 \line { \vcenter \manGuard \hspace #1 \vcenter "\\manGuard" }
    \box \pad-markup #1 \line { \vcenter \manHealthWorker \hspace #1 \vcenter "\\manHealthWorker" }
    \box \pad-markup #1 \line { \vcenter \manInLotusPosition \hspace #1 \vcenter "\\manInLotusPosition" }
    \box \pad-markup #1 \line { \vcenter \manInManualWheelchair \hspace #1 \vcenter "\\manInManualWheelchair" }
    \box \pad-markup #1 \line { \vcenter \manInManualWheelchairFacingRight \hspace #1 \vcenter "\\manInManualWheelchairFacingRight" }
    \box \pad-markup #1 \line { \vcenter \manInMotorizedWheelchair \hspace #1 \vcenter "\\manInMotorizedWheelchair" }
    \box \pad-markup #1 \line { \vcenter \manInMotorizedWheelchairFacingRight \hspace #1 \vcenter "\\manInMotorizedWheelchairFacingRight" }
    \box \pad-markup #1 \line { \vcenter \manInSteamyRoom \hspace #1 \vcenter "\\manInSteamyRoom" }
    \box \pad-markup #1 \line { \vcenter \manInTuxedo \hspace #1 \vcenter "\\manInTuxedo" }
    \box \pad-markup #1 \line { \vcenter \manJudge \hspace #1 \vcenter "\\manJudge" }
    \box \pad-markup #1 \line { \vcenter \manJuggling \hspace #1 \vcenter "\\manJuggling" }
    \box \pad-markup #1 \line { \vcenter \manKneeling \hspace #1 \vcenter "\\manKneeling" }
    \box \pad-markup #1 \line { \vcenter \manKneelingFacingRight \hspace #1 \vcenter "\\manKneelingFacingRight" }
    \box \pad-markup #1 \line { \vcenter \manLiftingWeights \hspace #1 \vcenter "\\manLiftingWeights" }
    \box \pad-markup #1 \line { \vcenter \manMage \hspace #1 \vcenter "\\manMage" }
    \box \pad-markup #1 \line { \vcenter \manMechanic \hspace #1 \vcenter "\\manMechanic" }
    \box \pad-markup #1 \line { \vcenter \manMountainBiking \hspace #1 \vcenter "\\manMountainBiking" }
    \box \pad-markup #1 \line { \vcenter \manOfficeWorker \hspace #1 \vcenter "\\manOfficeWorker" }
    \box \pad-markup #1 \line { \vcenter \manPilot \hspace #1 \vcenter "\\manPilot" }
    \box \pad-markup #1 \line { \vcenter \manPlayingHandball \hspace #1 \vcenter "\\manPlayingHandball" }
    \box \pad-markup #1 \line { \vcenter \manPlayingWaterPolo \hspace #1 \vcenter "\\manPlayingWaterPolo" }
    \box \pad-markup #1 \line { \vcenter \manPoliceOfficer \hspace #1 \vcenter "\\manPoliceOfficer" }
    \box \pad-markup #1 \line { \vcenter \manPouting \hspace #1 \vcenter "\\manPouting" }
    \box \pad-markup #1 \line { \vcenter \manRaisingHand \hspace #1 \vcenter "\\manRaisingHand" }
    \box \pad-markup #1 \line { \vcenter \manRedHair \hspace #1 \vcenter "\\manRedHair" }
    \box \pad-markup #1 \line { \vcenter \manRowingBoat \hspace #1 \vcenter "\\manRowingBoat" }
    \box \pad-markup #1 \line { \vcenter \manRunning \hspace #1 \vcenter "\\manRunning" }
    \box \pad-markup #1 \line { \vcenter \manRunningFacingRight \hspace #1 \vcenter "\\manRunningFacingRight" }
    \box \pad-markup #1 \line { \vcenter \manScientist \hspace #1 \vcenter "\\manScientist" }
    \box \pad-markup #1 \line { \vcenter \manShrugging \hspace #1 \vcenter "\\manShrugging" }
    \box \pad-markup #1 \line { \vcenter \manSinger \hspace #1 \vcenter "\\manSinger" }
    \box \pad-markup #1 \line { \vcenter \manStanding \hspace #1 \vcenter "\\manStanding" }
    \box \pad-markup #1 \line { \vcenter \manStudent \hspace #1 \vcenter "\\manStudent" }
    \box \pad-markup #1 \line { \vcenter \manSuperhero \hspace #1 \vcenter "\\manSuperhero" }
    \box \pad-markup #1 \line { \vcenter \manSupervillain \hspace #1 \vcenter "\\manSupervillain" }
    \box \pad-markup #1 \line { \vcenter \manSurfing \hspace #1 \vcenter "\\manSurfing" }
    \box \pad-markup #1 \line { \vcenter \manSwimming \hspace #1 \vcenter "\\manSwimming" }
    \box \pad-markup #1 \line { \vcenter \manTeacher \hspace #1 \vcenter "\\manTeacher" }
    \box \pad-markup #1 \line { \vcenter \manTechnologist \hspace #1 \vcenter "\\manTechnologist" }
    \box \pad-markup #1 \line { \vcenter \manTippingHand \hspace #1 \vcenter "\\manTippingHand" }
    \box \pad-markup #1 \line { \vcenter \manVampire \hspace #1 \vcenter "\\manVampire" }
    \box \pad-markup #1 \line { \vcenter \manWalking \hspace #1 \vcenter "\\manWalking" }
    \box \pad-markup #1 \line { \vcenter \manWalkingFacingRight \hspace #1 \vcenter "\\manWalkingFacingRight" }
    \box \pad-markup #1 \line { \vcenter \manWearingTurban \hspace #1 \vcenter "\\manWearingTurban" }
    \box \pad-markup #1 \line { \vcenter \manWhiteHair \hspace #1 \vcenter "\\manWhiteHair" }
    \box \pad-markup #1 \line { \vcenter \manWithVeil \hspace #1 \vcenter "\\manWithVeil" }
    \box \pad-markup #1 \line { \vcenter \manWithWhiteCane \hspace #1 \vcenter "\\manWithWhiteCane" }
    \box \pad-markup #1 \line { \vcenter \manWithWhiteCaneFacingRight \hspace #1 \vcenter "\\manWithWhiteCaneFacingRight" }
    \box \pad-markup #1 \line { \vcenter \manZombie \hspace #1 \vcenter "\\manZombie" }
    \box \pad-markup #1 \line { \vcenter \mechanic \hspace #1 \vcenter "\\mechanic" }
    \box \pad-markup #1 \line { \vcenter \mechanicalArm \hspace #1 \vcenter "\\mechanicalArm" }
    \box \pad-markup #1 \line { \vcenter \mechanicalLeg \hspace #1 \vcenter "\\mechanicalLeg" }
    \box \pad-markup #1 \line { \vcenter \menHoldingHands \hspace #1 \vcenter "\\menHoldingHands" }
    \box \pad-markup #1 \line { \vcenter \menWithBunnyEars \hspace #1 \vcenter "\\menWithBunnyEars" }
    \box \pad-markup #1 \line { \vcenter \menWrestling \hspace #1 \vcenter "\\menWrestling" }
    \box \pad-markup #1 \line { \vcenter \mermaid \hspace #1 \vcenter "\\mermaid" }
    \box \pad-markup #1 \line { \vcenter \merman \hspace #1 \vcenter "\\merman" }
    \box \pad-markup #1 \line { \vcenter \merperson \hspace #1 \vcenter "\\merperson" }
    \box \pad-markup #1 \line { \vcenter \middleFinger \hspace #1 \vcenter "\\middleFinger" }
    \box \pad-markup #1 \line { \vcenter \mouth \hspace #1 \vcenter "\\mouth" }
    \box \pad-markup #1 \line { \vcenter \mrsClaus \hspace #1 \vcenter "\\mrsClaus" }
    \box \pad-markup #1 \line { \vcenter \mxClaus \hspace #1 \vcenter "\\mxClaus" }
    \box \pad-markup #1 \line { \vcenter \nailPolish \hspace #1 \vcenter "\\nailPolish" }
    \box \pad-markup #1 \line { \vcenter \ninja \hspace #1 \vcenter "\\ninja" }
    \box \pad-markup #1 \line { \vcenter \nose \hspace #1 \vcenter "\\nose" }
    \box \pad-markup #1 \line { \vcenter \officeWorker \hspace #1 \vcenter "\\officeWorker" }
    \box \pad-markup #1 \line { \vcenter \okHand \hspace #1 \vcenter "\\okHand" }
    \box \pad-markup #1 \line { \vcenter \oldMan \hspace #1 \vcenter "\\oldMan" }
    \box \pad-markup #1 \line { \vcenter \oldWoman \hspace #1 \vcenter "\\oldWoman" }
    \box \pad-markup #1 \line { \vcenter \olderPerson \hspace #1 \vcenter "\\olderPerson" }
    \box \pad-markup #1 \line { \vcenter \oncomingFist \hspace #1 \vcenter "\\oncomingFist" }
    \box \pad-markup #1 \line { \vcenter \openHands \hspace #1 \vcenter "\\openHands" }
    \box \pad-markup #1 \line { \vcenter \palmDownHand \hspace #1 \vcenter "\\palmDownHand" }
    \box \pad-markup #1 \line { \vcenter \palmUpHand \hspace #1 \vcenter "\\palmUpHand" }
    \box \pad-markup #1 \line { \vcenter \palmsUpTogether \hspace #1 \vcenter "\\palmsUpTogether" }
    \box \pad-markup #1 \line { \vcenter \peopleHoldingHands \hspace #1 \vcenter "\\peopleHoldingHands" }
    \box \pad-markup #1 \line { \vcenter \peopleHugging \hspace #1 \vcenter "\\peopleHugging" }
    \box \pad-markup #1 \line { \vcenter \peopleWithBunnyEars \hspace #1 \vcenter "\\peopleWithBunnyEars" }
    \box \pad-markup #1 \line { \vcenter \peopleWrestling \hspace #1 \vcenter "\\peopleWrestling" }
    \box \pad-markup #1 \line { \vcenter \person \hspace #1 \vcenter "\\person" }
    \box \pad-markup #1 \line { \vcenter \personBald \hspace #1 \vcenter "\\personBald" }
    \box \pad-markup #1 \line { \vcenter \personBeard \hspace #1 \vcenter "\\personBeard" }
    \box \pad-markup #1 \line { \vcenter \personBiking \hspace #1 \vcenter "\\personBiking" }
    \box \pad-markup #1 \line { \vcenter \personBlondHair \hspace #1 \vcenter "\\personBlondHair" }
    \box \pad-markup #1 \line { \vcenter \personBouncingBall \hspace #1 \vcenter "\\personBouncingBall" }
    \box \pad-markup #1 \line { \vcenter \personBowing \hspace #1 \vcenter "\\personBowing" }
    \box \pad-markup #1 \line { \vcenter \personCartwheeling \hspace #1 \vcenter "\\personCartwheeling" }
    \box \pad-markup #1 \line { \vcenter \personClimbing \hspace #1 \vcenter "\\personClimbing" }
    \box \pad-markup #1 \line { \vcenter \personCurlyHair \hspace #1 \vcenter "\\personCurlyHair" }
    \box \pad-markup #1 \line { \vcenter \personFacepalming \hspace #1 \vcenter "\\personFacepalming" }
    \box \pad-markup #1 \line { \vcenter \personFeedingBaby \hspace #1 \vcenter "\\personFeedingBaby" }
    \box \pad-markup #1 \line { \vcenter \personFencing \hspace #1 \vcenter "\\personFencing" }
    \box \pad-markup #1 \line { \vcenter \personFrowning \hspace #1 \vcenter "\\personFrowning" }
    \box \pad-markup #1 \line { \vcenter \personGesturingNo \hspace #1 \vcenter "\\personGesturingNo" }
    \box \pad-markup #1 \line { \vcenter \personGesturingOk \hspace #1 \vcenter "\\personGesturingOk" }
    \box \pad-markup #1 \line { \vcenter \personGettingHaircut \hspace #1 \vcenter "\\personGettingHaircut" }
    \box \pad-markup #1 \line { \vcenter \personGettingMassage \hspace #1 \vcenter "\\personGettingMassage" }
    \box \pad-markup #1 \line { \vcenter \personGolfing \hspace #1 \vcenter "\\personGolfing" }
    \box \pad-markup #1 \line { \vcenter \personInBed \hspace #1 \vcenter "\\personInBed" }
    \box \pad-markup #1 \line { \vcenter \personInLotusPosition \hspace #1 \vcenter "\\personInLotusPosition" }
    \box \pad-markup #1 \line { \vcenter \personInManualWheelchair \hspace #1 \vcenter "\\personInManualWheelchair" }
    \box \pad-markup #1 \line { \vcenter \personInManualWheelchairFacingRight \hspace #1 \vcenter "\\personInManualWheelchairFacingRight" }
    \box \pad-markup #1 \line { \vcenter \personInMotorizedWheelchair \hspace #1 \vcenter "\\personInMotorizedWheelchair" }
    \box \pad-markup #1 \line { \vcenter \personInMotorizedWheelchairFacingRight \hspace #1 \vcenter "\\personInMotorizedWheelchairFacingRight" }
    \box \pad-markup #1 \line { \vcenter \personInSteamyRoom \hspace #1 \vcenter "\\personInSteamyRoom" }
    \box \pad-markup #1 \line { \vcenter \personInSuitLevitating \hspace #1 \vcenter "\\personInSuitLevitating" }
    \box \pad-markup #1 \line { \vcenter \personInTuxedo \hspace #1 \vcenter "\\personInTuxedo" }
    \box \pad-markup #1 \line { \vcenter \personJuggling \hspace #1 \vcenter "\\personJuggling" }
    \box \pad-markup #1 \line { \vcenter \personKneeling \hspace #1 \vcenter "\\personKneeling" }
    \box \pad-markup #1 \line { \vcenter \personKneelingFacingRight \hspace #1 \vcenter "\\personKneelingFacingRight" }
    \box \pad-markup #1 \line { \vcenter \personLiftingWeights \hspace #1 \vcenter "\\personLiftingWeights" }
    \box \pad-markup #1 \line { \vcenter \personMountainBiking \hspace #1 \vcenter "\\personMountainBiking" }
    \box \pad-markup #1 \line { \vcenter \personPlayingHandball \hspace #1 \vcenter "\\personPlayingHandball" }
    \box \pad-markup #1 \line { \vcenter \personPlayingWaterPolo \hspace #1 \vcenter "\\personPlayingWaterPolo" }
    \box \pad-markup #1 \line { \vcenter \personPouting \hspace #1 \vcenter "\\personPouting" }
    \box \pad-markup #1 \line { \vcenter \personRaisingHand \hspace #1 \vcenter "\\personRaisingHand" }
    \box \pad-markup #1 \line { \vcenter \personRedHair \hspace #1 \vcenter "\\personRedHair" }
    \box \pad-markup #1 \line { \vcenter \personRowingBoat \hspace #1 \vcenter "\\personRowingBoat" }
    \box \pad-markup #1 \line { \vcenter \personRunning \hspace #1 \vcenter "\\personRunning" }
    \box \pad-markup #1 \line { \vcenter \personRunningFacingRight \hspace #1 \vcenter "\\personRunningFacingRight" }
    \box \pad-markup #1 \line { \vcenter \personShrugging \hspace #1 \vcenter "\\personShrugging" }
    \box \pad-markup #1 \line { \vcenter \personStanding \hspace #1 \vcenter "\\personStanding" }
    \box \pad-markup #1 \line { \vcenter \personSurfing \hspace #1 \vcenter "\\personSurfing" }
    \box \pad-markup #1 \line { \vcenter \personSwimming \hspace #1 \vcenter "\\personSwimming" }
    \box \pad-markup #1 \line { \vcenter \personTakingBath \hspace #1 \vcenter "\\personTakingBath" }
    \box \pad-markup #1 \line { \vcenter \personTippingHand \hspace #1 \vcenter "\\personTippingHand" }
    \box \pad-markup #1 \line { \vcenter \personWalking \hspace #1 \vcenter "\\personWalking" }
    \box \pad-markup #1 \line { \vcenter \personWalkingFacingRight \hspace #1 \vcenter "\\personWalkingFacingRight" }
    \box \pad-markup #1 \line { \vcenter \personWearingTurban \hspace #1 \vcenter "\\personWearingTurban" }
    \box \pad-markup #1 \line { \vcenter \personWhiteHair \hspace #1 \vcenter "\\personWhiteHair" }
    \box \pad-markup #1 \line { \vcenter \personWithCrown \hspace #1 \vcenter "\\personWithCrown" }
    \box \pad-markup #1 \line { \vcenter \personWithSkullcap \hspace #1 \vcenter "\\personWithSkullcap" }
    \box \pad-markup #1 \line { \vcenter \personWithVeil \hspace #1 \vcenter "\\personWithVeil" }
    \box \pad-markup #1 \line { \vcenter \personWithWhiteCane \hspace #1 \vcenter "\\personWithWhiteCane" }
    \box \pad-markup #1 \line { \vcenter \personWithWhiteCaneFacingRight \hspace #1 \vcenter "\\personWithWhiteCaneFacingRight" }
    \box \pad-markup #1 \line { \vcenter \pilot \hspace #1 \vcenter "\\pilot" }
    \box \pad-markup #1 \line { \vcenter \pinchedFingers \hspace #1 \vcenter "\\pinchedFingers" }
    \box \pad-markup #1 \line { \vcenter \pinchingHand \hspace #1 \vcenter "\\pinchingHand" }
    \box \pad-markup #1 \line { \vcenter \policeOfficer \hspace #1 \vcenter "\\policeOfficer" }
    \box \pad-markup #1 \line { \vcenter \pregnantMan \hspace #1 \vcenter "\\pregnantMan" }
    \box \pad-markup #1 \line { \vcenter \pregnantPerson \hspace #1 \vcenter "\\pregnantPerson" }
    \box \pad-markup #1 \line { \vcenter \pregnantWoman \hspace #1 \vcenter "\\pregnantWoman" }
    \box \pad-markup #1 \line { \vcenter \prince \hspace #1 \vcenter "\\prince" }
    \box \pad-markup #1 \line { \vcenter \princess \hspace #1 \vcenter "\\princess" }
    \box \pad-markup #1 \line { \vcenter \raisedBackOfHand \hspace #1 \vcenter "\\raisedBackOfHand" }
    \box \pad-markup #1 \line { \vcenter \raisedFist \hspace #1 \vcenter "\\raisedFist" }
    \box \pad-markup #1 \line { \vcenter \raisedHand \hspace #1 \vcenter "\\raisedHand" }
    \box \pad-markup #1 \line { \vcenter \raisingHands \hspace #1 \vcenter "\\raisingHands" }
    \box \pad-markup #1 \line { \vcenter \rightFacingFist \hspace #1 \vcenter "\\rightFacingFist" }
    \box \pad-markup #1 \line { \vcenter \rightwardsHand \hspace #1 \vcenter "\\rightwardsHand" }
    \box \pad-markup #1 \line { \vcenter \rightwardsPushingHand \hspace #1 \vcenter "\\rightwardsPushingHand" }
    \box \pad-markup #1 \line { \vcenter \santaClaus \hspace #1 \vcenter "\\santaClaus" }
    \box \pad-markup #1 \line { \vcenter \scientist \hspace #1 \vcenter "\\scientist" }
    \box \pad-markup #1 \line { \vcenter \selfie \hspace #1 \vcenter "\\selfie" }
    \box \pad-markup #1 \line { \vcenter \signOfTheHorns \hspace #1 \vcenter "\\signOfTheHorns" }
    \box \pad-markup #1 \line { \vcenter \singer \hspace #1 \vcenter "\\singer" }
    \box \pad-markup #1 \line { \vcenter \skier \hspace #1 \vcenter "\\skier" }
    \box \pad-markup #1 \line { \vcenter \snowboarder \hspace #1 \vcenter "\\snowboarder" }
    \box \pad-markup #1 \line { \vcenter \speakingHead \hspace #1 \vcenter "\\speakingHead" }
    \box \pad-markup #1 \line { \vcenter \student \hspace #1 \vcenter "\\student" }
    \box \pad-markup #1 \line { \vcenter \superhero \hspace #1 \vcenter "\\superhero" }
    \box \pad-markup #1 \line { \vcenter \supervillain \hspace #1 \vcenter "\\supervillain" }
    \box \pad-markup #1 \line { \vcenter \teacher \hspace #1 \vcenter "\\teacher" }
    \box \pad-markup #1 \line { \vcenter \technologist \hspace #1 \vcenter "\\technologist" }
    \box \pad-markup #1 \line { \vcenter \thumbsDown \hspace #1 \vcenter "\\thumbsDown" }
    \box \pad-markup #1 \line { \vcenter \thumbsUp \hspace #1 \vcenter "\\thumbsUp" }
    \box \pad-markup #1 \line { \vcenter \tongue \hspace #1 \vcenter "\\tongue" }
    \box \pad-markup #1 \line { \vcenter \tooth \hspace #1 \vcenter "\\tooth" }
    \box \pad-markup #1 \line { \vcenter \troll \hspace #1 \vcenter "\\troll" }
    \box \pad-markup #1 \line { \vcenter \vampire \hspace #1 \vcenter "\\vampire" }
    \box \pad-markup #1 \line { \vcenter \victoryHand \hspace #1 \vcenter "\\victoryHand" }
    \box \pad-markup #1 \line { \vcenter \vulcanSalute \hspace #1 \vcenter "\\vulcanSalute" }
    \box \pad-markup #1 \line { \vcenter \wavingHand \hspace #1 \vcenter "\\wavingHand" }
    \box \pad-markup #1 \line { \vcenter \woman \hspace #1 \vcenter "\\woman" }
    \box \pad-markup #1 \line { \vcenter \womanAndManHoldingHands \hspace #1 \vcenter "\\womanAndManHoldingHands" }
    \box \pad-markup #1 \line { \vcenter \womanArtist \hspace #1 \vcenter "\\womanArtist" }
    \box \pad-markup #1 \line { \vcenter \womanAstronaut \hspace #1 \vcenter "\\womanAstronaut" }
    \box \pad-markup #1 \line { \vcenter \womanBald \hspace #1 \vcenter "\\womanBald" }
    \box \pad-markup #1 \line { \vcenter \womanBeard \hspace #1 \vcenter "\\womanBeard" }
    \box \pad-markup #1 \line { \vcenter \womanBiking \hspace #1 \vcenter "\\womanBiking" }
    \box \pad-markup #1 \line { \vcenter \womanBlondHair \hspace #1 \vcenter "\\womanBlondHair" }
    \box \pad-markup #1 \line { \vcenter \womanBouncingBall \hspace #1 \vcenter "\\womanBouncingBall" }
    \box \pad-markup #1 \line { \vcenter \womanBowing \hspace #1 \vcenter "\\womanBowing" }
    \box \pad-markup #1 \line { \vcenter \womanCartwheeling \hspace #1 \vcenter "\\womanCartwheeling" }
    \box \pad-markup #1 \line { \vcenter \womanClimbing \hspace #1 \vcenter "\\womanClimbing" }
    \box \pad-markup #1 \line { \vcenter \womanConstructionWorker \hspace #1 \vcenter "\\womanConstructionWorker" }
    \box \pad-markup #1 \line { \vcenter \womanCook \hspace #1 \vcenter "\\womanCook" }
    \box \pad-markup #1 \line { \vcenter \womanCurlyHair \hspace #1 \vcenter "\\womanCurlyHair" }
    \box \pad-markup #1 \line { \vcenter \womanDancing \hspace #1 \vcenter "\\womanDancing" }
    \box \pad-markup #1 \line { \vcenter \womanDetective \hspace #1 \vcenter "\\womanDetective" }
    \box \pad-markup #1 \line { \vcenter \womanElf \hspace #1 \vcenter "\\womanElf" }
    \box \pad-markup #1 \line { \vcenter \womanFacepalming \hspace #1 \vcenter "\\womanFacepalming" }
    \box \pad-markup #1 \line { \vcenter \womanFactoryWorker \hspace #1 \vcenter "\\womanFactoryWorker" }
    \box \pad-markup #1 \line { \vcenter \womanFairy \hspace #1 \vcenter "\\womanFairy" }
    \box \pad-markup #1 \line { \vcenter \womanFarmer \hspace #1 \vcenter "\\womanFarmer" }
    \box \pad-markup #1 \line { \vcenter \womanFeedingBaby \hspace #1 \vcenter "\\womanFeedingBaby" }
    \box \pad-markup #1 \line { \vcenter \womanFirefighter \hspace #1 \vcenter "\\womanFirefighter" }
    \box \pad-markup #1 \line { \vcenter \womanFrowning \hspace #1 \vcenter "\\womanFrowning" }
    \box \pad-markup #1 \line { \vcenter \womanGenie \hspace #1 \vcenter "\\womanGenie" }
    \box \pad-markup #1 \line { \vcenter \womanGesturingNo \hspace #1 \vcenter "\\womanGesturingNo" }
    \box \pad-markup #1 \line { \vcenter \womanGesturingOk \hspace #1 \vcenter "\\womanGesturingOk" }
    \box \pad-markup #1 \line { \vcenter \womanGettingHaircut \hspace #1 \vcenter "\\womanGettingHaircut" }
    \box \pad-markup #1 \line { \vcenter \womanGettingMassage \hspace #1 \vcenter "\\womanGettingMassage" }
    \box \pad-markup #1 \line { \vcenter \womanGolfing \hspace #1 \vcenter "\\womanGolfing" }
    \box \pad-markup #1 \line { \vcenter \womanGuard \hspace #1 \vcenter "\\womanGuard" }
    \box \pad-markup #1 \line { \vcenter \womanHealthWorker \hspace #1 \vcenter "\\womanHealthWorker" }
    \box \pad-markup #1 \line { \vcenter \womanInLotusPosition \hspace #1 \vcenter "\\womanInLotusPosition" }
    \box \pad-markup #1 \line { \vcenter \womanInManualWheelchair \hspace #1 \vcenter "\\womanInManualWheelchair" }
    \box \pad-markup #1 \line { \vcenter \womanInManualWheelchairFacingRight \hspace #1 \vcenter "\\womanInManualWheelchairFacingRight" }
    \box \pad-markup #1 \line { \vcenter \womanInMotorizedWheelchair \hspace #1 \vcenter "\\womanInMotorizedWheelchair" }
    \box \pad-markup #1 \line { \vcenter \womanInMotorizedWheelchairFacingRight \hspace #1 \vcenter "\\womanInMotorizedWheelchairFacingRight" }
    \box \pad-markup #1 \line { \vcenter \womanInSteamyRoom \hspace #1 \vcenter "\\womanInSteamyRoom" }
    \box \pad-markup #1 \line { \vcenter \womanInTuxedo \hspace #1 \vcenter "\\womanInTuxedo" }
    \box \pad-markup #1 \line { \vcenter \womanJudge \hspace #1 \vcenter "\\womanJudge" }
    \box \pad-markup #1 \line { \vcenter \womanJuggling \hspace #1 \vcenter "\\womanJuggling" }
    \box \pad-markup #1 \line { \vcenter \womanKneeling \hspace #1 \vcenter "\\womanKneeling" }
    \box \pad-markup #1 \line { \vcenter \womanKneelingFacingRight \hspace #1 \vcenter "\\womanKneelingFacingRight" }
    \box \pad-markup #1 \line { \vcenter \womanLiftingWeights \hspace #1 \vcenter "\\womanLiftingWeights" }
    \box \pad-markup #1 \line { \vcenter \womanMage \hspace #1 \vcenter "\\womanMage" }
    \box \pad-markup #1 \line { \vcenter \womanMechanic \hspace #1 \vcenter "\\womanMechanic" }
    \box \pad-markup #1 \line { \vcenter \womanMountainBiking \hspace #1 \vcenter "\\womanMountainBiking" }
    \box \pad-markup #1 \line { \vcenter \womanOfficeWorker \hspace #1 \vcenter "\\womanOfficeWorker" }
    \box \pad-markup #1 \line { \vcenter \womanPilot \hspace #1 \vcenter "\\womanPilot" }
    \box \pad-markup #1 \line { \vcenter \womanPlayingHandball \hspace #1 \vcenter "\\womanPlayingHandball" }
    \box \pad-markup #1 \line { \vcenter \womanPlayingWaterPolo \hspace #1 \vcenter "\\womanPlayingWaterPolo" }
    \box \pad-markup #1 \line { \vcenter \womanPoliceOfficer \hspace #1 \vcenter "\\womanPoliceOfficer" }
    \box \pad-markup #1 \line { \vcenter \womanPouting \hspace #1 \vcenter "\\womanPouting" }
    \box \pad-markup #1 \line { \vcenter \womanRaisingHand \hspace #1 \vcenter "\\womanRaisingHand" }
    \box \pad-markup #1 \line { \vcenter \womanRedHair \hspace #1 \vcenter "\\womanRedHair" }
    \box \pad-markup #1 \line { \vcenter \womanRowingBoat \hspace #1 \vcenter "\\womanRowingBoat" }
    \box \pad-markup #1 \line { \vcenter \womanRunning \hspace #1 \vcenter "\\womanRunning" }
    \box \pad-markup #1 \line { \vcenter \womanRunningFacingRight \hspace #1 \vcenter "\\womanRunningFacingRight" }
    \box \pad-markup #1 \line { \vcenter \womanScientist \hspace #1 \vcenter "\\womanScientist" }
    \box \pad-markup #1 \line { \vcenter \womanShrugging \hspace #1 \vcenter "\\womanShrugging" }
    \box \pad-markup #1 \line { \vcenter \womanSinger \hspace #1 \vcenter "\\womanSinger" }
    \box \pad-markup #1 \line { \vcenter \womanStanding \hspace #1 \vcenter "\\womanStanding" }
    \box \pad-markup #1 \line { \vcenter \womanStudent \hspace #1 \vcenter "\\womanStudent" }
    \box \pad-markup #1 \line { \vcenter \womanSuperhero \hspace #1 \vcenter "\\womanSuperhero" }
    \box \pad-markup #1 \line { \vcenter \womanSupervillain \hspace #1 \vcenter "\\womanSupervillain" }
    \box \pad-markup #1 \line { \vcenter \womanSurfing \hspace #1 \vcenter "\\womanSurfing" }
    \box \pad-markup #1 \line { \vcenter \womanSwimming \hspace #1 \vcenter "\\womanSwimming" }
    \box \pad-markup #1 \line { \vcenter \womanTeacher \hspace #1 \vcenter "\\womanTeacher" }
    \box \pad-markup #1 \line { \vcenter \womanTechnologist \hspace #1 \vcenter "\\womanTechnologist" }
    \box \pad-markup #1 \line { \vcenter \womanTippingHand \hspace #1 \vcenter "\\womanTippingHand" }
    \box \pad-markup #1 \line { \vcenter \womanVampire \hspace #1 \vcenter "\\womanVampire" }
    \box \pad-markup #1 \line { \vcenter \womanWalking \hspace #1 \vcenter "\\womanWalking" }
    \box \pad-markup #1 \line { \vcenter \womanWalkingFacingRight \hspace #1 \vcenter "\\womanWalkingFacingRight" }
    \box \pad-markup #1 \line { \vcenter \womanWearingTurban \hspace #1 \vcenter "\\womanWearingTurban" }
    \box \pad-markup #1 \line { \vcenter \womanWhiteHair \hspace #1 \vcenter "\\womanWhiteHair" }
    \box \pad-markup #1 \line { \vcenter \womanWithHeadscarf \hspace #1 \vcenter "\\womanWithHeadscarf" }
    \box \pad-markup #1 \line { \vcenter \womanWithVeil \hspace #1 \vcenter "\\womanWithVeil" }
    \box \pad-markup #1 \line { \vcenter \womanWithWhiteCane \hspace #1 \vcenter "\\womanWithWhiteCane" }
    \box \pad-markup #1 \line { \vcenter \womanWithWhiteCaneFacingRight \hspace #1 \vcenter "\\womanWithWhiteCaneFacingRight" }
    \box \pad-markup #1 \line { \vcenter \womanZombie \hspace #1 \vcenter "\\womanZombie" }
    \box \pad-markup #1 \line { \vcenter \womenHoldingHands \hspace #1 \vcenter "\\womenHoldingHands" }
    \box \pad-markup #1 \line { \vcenter \womenWithBunnyEars \hspace #1 \vcenter "\\womenWithBunnyEars" }
    \box \pad-markup #1 \line { \vcenter \womenWrestling \hspace #1 \vcenter "\\womenWrestling" }
    \box \pad-markup #1 \line { \vcenter \writingHand \hspace #1 \vcenter "\\writingHand" }
    \box \pad-markup #1 \line { \vcenter \zombie \hspace #1 \vcenter "\\zombie" }
  }
}